## General pipeline parameters:
## For optional parameters either leave empty string ("") or comment out ("#") the parameter

# working directory (required):
workdir: "/scratch/prj/bcn_synaptopathy/pipeline-isoforms-ONT-stringtie/"

# prefix of all output files (optional; default = "sample")
sample_name: "barcode03"

# reference genome as fasta (required):
genome: "/scratch/prj/bcn_synaptopathy/references/GRCh38.primary_assembly.genome.fa"

# ONT reads in fastq format (required):
reads_fastq: "/scratch/prj/bcn_synaptopathy/input_fastq/"

# The path above is a directory, find and concatenate fastq files:
concatenate_reads: True

# Process cDNA reads using pychopper, turn off for direct RNA:
run_pychopper: True

# kit used (e.g. PCS109,PCS110,PCS111,LSK114). Default (PCS109)
kit: "PCS111"

# Options passed to pychopper:
pychopper_opts: ""

# Options passed to minimap2:
minimap2_opts: "-uf -k14 --MD"

# threads (default = 30)
threads: 30

# Use exiting annotation as guide for stringtie2:
use_guide_annotation: True

# reference annotation as GTF (required if use_guide_annotation = true):
annotation: "/scratch/prj/bcn_synaptopathy/references/gencode.v49.annotation.gtf"

# Options passed to stringtie2:
stringtie_opts: "-f 0.005"
